### ISSUE TITLE
Add nftSaleCallback call to the buyTokens function

### ISSUE THREAD

**Issue by NikitaBerezhnoy** [LeagueDAO/NomoDropMechanic#17] opened 2021-11-01 17:55 UTC
In the NomoVault ( represented as the strategyContractAddress in the NomoPlayersDropMechanic) we have this fuction:
```    /**
     * @notice Function that is called by sales contract as callback in order to deposit funds to strategy
     * @param tokensIds List of token IDs sold
     * @param prices Prices of sold tokens respectively (as wei)
     */
    function nftSaleCallback(
        uint256[] memory tokensIds,
        uint256[] memory prices
    ) external onlySales
```

This function is needed to know the exact amount of DAI paid to the NomoVault/Strategy per token + to know tokens league id, so we can divide DAI between leagues, so each will receive its own rewards which depend on the amount of sales. Also DAI must be approved to the NomoVault contract instead of transfering them, so we can avoid mistake with DAI amount.

You can look at the NomoVault contract here: https://github.com/LeagueDAO/nomo-strategy/blob/implement-strategy/contracts/NomoVault.sol

**Comment by HristiyanG** [comment] 2021-11-02 09:14
Hey Nikita,
Thanks for raising this with us! It's still a bit unclear of how we should proceed but i'll try to address all my questions i currently have in one shot so hopefully we can speed up the process of reaching to an agreement any time soon. So here are my 2 cents: 
- all tokens will be with a static price, meaning that we can the totalPrice as param to NomoVault, or simply the tokenPrice to be sent and based on that to do the math at your end? Also if we can achieve sending 1 array less as param would be more optimal imho
- <i>"Also DAI must be approved to the NomoVault contract instead of transfering them, so we can avoid mistake with DAI amount."</i>
	- i am not sure I fully understand this one. Let's try to break it up from my perspective. We should not call `transferFrom` from the dropMechanic, but give approval to the strategy contract so it will transfer the funds instead?. Please confirm.
	- We were currently splitting the amount 80/20 to strategy/daoWallet Are we going `approve` the total price to the NomoVault or we should split amount again . if that is the case:
		- do we still need to `transfer` a portion of the  funds to the daoWallet from the dropMechanic, or we need to `approve` the fraction to this one as well?

**Comment by NikitaBerezhnoy** [comment] 2021-11-04 12:20
I created PR where you see my version of how this can be implemented. Also updated Strategy mock with the callback function mock. About first point - we added price array for future compatibility, because we don't know how funds can be transfered to the Strategy in future.

**Comment by HristiyanG** [comment] 2021-11-04 13:48
Thanks for raising the draft. I think i grasped the idea just some topics i'd like to clarify. 
As this contract was intended for transferring tokens and funds respectively, not holding the tokens at any given time. How long do you think they are going to be stored in the NomoDropMechanic? Could not we just transfer the tokens to where they should belong? If eventually we reach to a conclusion this is the best option - did you intentionally used `approve` when calling the ERC20 as would be error prone in our case imo? Better use `increaseAllowance`. Just thinking out loud..

**Comment by NikitaBerezhnoy** [comment] 2021-11-04 14:10
NomoVault contract will immediatly transfer tokens from the NomoDropMechanic inside the callback function, so practically your contract won`t hold any tokens. Also approve here is safe because of the immedaite transfer, but you can use increaseAllowance if you think it's better here.

**Comment by HristiyanG** [comment] 2021-11-04 14:16
If that's the case, would not it be better if we `transfer` the `totalPrice` to the `want` contact directly, rather then using `approve` && `transfer`?

**Comment by NikitaBerezhnoy** [comment] 2021-11-04 17:13
Because we need to be sure that tokens are actually transfered to our side and there is no mistake in amounts. This check must be somewhere, so why not use default ERC20 functionality for this case

**Closed as completed** 2021-11-05 09:13 UTC

**Comment by HristiyanG** [comment] 2021-11-05 13:11
Still not sure how we did not use the <i>use default ERC20 functionality </i>. We apply the changes as per your example as we are running out of time. Thanks for your assistance
